--- Builds/Linux/Makefile	2011-09-20 13:04:58.000000000 -0700
+++ Builds/Linux/Makefile	2011-09-20 14:11:49.000000000 -0700
@@ -17,12 +17,12 @@
   LIBDIR := build
   OBJDIR := build/intermediate/Debug
   OUTDIR := build
-  CPPFLAGS := $(DEPFLAGS) -D "LINUX=1" -D "DEBUG=1" -D "_DEBUG=1" -D "JUCER_LINUX_MAKE_7346DA2A=1" -I "~/SDKs/vstsdk2.4" -I "/usr/include" -I "/usr/include/freetype2" -I "../../oscpack" -I "../../JuceLibraryCode"
+  CPPFLAGS := $(DEPFLAGS) -D "LINUX=1" -D "DEBUG=1" -D "_DEBUG=1" -D "JUCER_LINUX_MAKE_7346DA2A=1" -I "/usr/include/vst24" -I "/usr/include" -I "/usr/include/freetype2" -I "/usr/include/oscpack" -I "../../JuceLibraryCode"
   CFLAGS += $(CPPFLAGS) $(TARGET_ARCH) -g -ggdb -fPIC -O0
   CXXFLAGS += $(CFLAGS) 
   LDFLAGS += -L$(BINDIR) -L$(LIBDIR) -shared -L"/usr/X11R6/lib/" -L"../../../../../../Documents/bin" -lfreetype -lpthread -lrt -lX11 -lGL -lGLU -lXinerama -lasound 
   LDDEPS :=
-  RESFLAGS :=  -D "LINUX=1" -D "DEBUG=1" -D "_DEBUG=1" -D "JUCER_LINUX_MAKE_7346DA2A=1" -I "~/SDKs/vstsdk2.4" -I "/usr/include" -I "/usr/include/freetype2" -I "../../oscpack" -I "../../JuceLibraryCode"
+  RESFLAGS :=  -D "LINUX=1" -D "DEBUG=1" -D "_DEBUG=1" -D "JUCER_LINUX_MAKE_7346DA2A=1" -I "/usr/include/vst24" -I "/usr/include" -I "/usr/include/freetype2" -I "/usr/include/oscpack" -I "../../JuceLibraryCode"
   TARGET := mlrVST.so
   BLDCMD = $(CXX) -o $(OUTDIR)/$(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(TARGET_ARCH)
 endif
@@ -32,12 +32,12 @@
   LIBDIR := build
   OBJDIR := build/intermediate/Release
   OUTDIR := build
-  CPPFLAGS := $(DEPFLAGS) -D "LINUX=1" -D "NDEBUG=1" -D "JUCER_LINUX_MAKE_7346DA2A=1" -I "~/SDKs/vstsdk2.4" -I "/usr/include" -I "/usr/include/freetype2" -I "../../oscpack" -I "../../JuceLibraryCode"
+  CPPFLAGS := $(DEPFLAGS) -D "LINUX=1" -D "NDEBUG=1" -D "JUCER_LINUX_MAKE_7346DA2A=1" -I "/usr/include/vst24" -I "/usr/include" -I "/usr/include/freetype2" -I "/usr/include/oscpack" -I "../../JuceLibraryCode"
   CFLAGS += $(CPPFLAGS) $(TARGET_ARCH) -fPIC -Os
   CXXFLAGS += $(CFLAGS) 
   LDFLAGS += -L$(BINDIR) -L$(LIBDIR) -shared -L"/usr/X11R6/lib/" -L"../../../../../../Documents/bin" -lfreetype -lpthread -lrt -lX11 -lGL -lGLU -lXinerama -lasound 
   LDDEPS :=
-  RESFLAGS :=  -D "LINUX=1" -D "NDEBUG=1" -D "JUCER_LINUX_MAKE_7346DA2A=1" -I "~/SDKs/vstsdk2.4" -I "/usr/include" -I "/usr/include/freetype2" -I "../../oscpack" -I "../../JuceLibraryCode"
+  RESFLAGS :=  -D "LINUX=1" -D "NDEBUG=1" -D "JUCER_LINUX_MAKE_7346DA2A=1" -I "/usr/include/vst24" -I "/usr/include" -I "/usr/include/freetype2" -I "/usr/include/oscpack" -I "../../JuceLibraryCode"
   TARGET := mlrVST.so
   BLDCMD = $(CXX) -o $(OUTDIR)/$(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(TARGET_ARCH)
 endif
@@ -80,37 +80,37 @@
         -@rm -rf $(OBJDIR)/*
         -@rm -rf $(OBJDIR)
 
-$(OBJDIR)/IpEndpointName_d4cc3aed.o: ../../oscpack/ip/IpEndpointName.cpp
+$(OBJDIR)/IpEndpointName_d4cc3aed.o: /usr/include/oscpack/ip/IpEndpointName.cpp
         -@mkdir -p $(OBJDIR)
         @echo "Compiling IpEndpointName.cpp"
         @$(CXX) $(CXXFLAGS) -o "$@" -c "$<"
 
-$(OBJDIR)/NetworkingUtils_571a8d2d.o: ../../oscpack/ip/win32/NetworkingUtils.cpp
+$(OBJDIR)/NetworkingUtils_571a8d2d.o: /usr/include/oscpack/ip/win32/NetworkingUtils.cpp
         -@mkdir -p $(OBJDIR)
         @echo "Compiling NetworkingUtils.cpp"
         @$(CXX) $(CXXFLAGS) -o "$@" -c "$<"
 
-$(OBJDIR)/UdpSocket_34dc4264.o: ../../oscpack/ip/win32/UdpSocket.cpp
+$(OBJDIR)/UdpSocket_34dc4264.o: /usr/include/oscpack/ip/win32/UdpSocket.cpp
         -@mkdir -p $(OBJDIR)
         @echo "Compiling UdpSocket.cpp"
         @$(CXX) $(CXXFLAGS) -o "$@" -c "$<"
 
-$(OBJDIR)/OscOutboundPacketStream_595b04c5.o: ../../oscpack/osc/OscOutboundPacketStream.cpp
+$(OBJDIR)/OscOutboundPacketStream_595b04c5.o: /usr/include/oscpack/osc/OscOutboundPacketStream.cpp
         -@mkdir -p $(OBJDIR)
         @echo "Compiling OscOutboundPacketStream.cpp"
         @$(CXX) $(CXXFLAGS) -o "$@" -c "$<"
 
-$(OBJDIR)/OscPrintReceivedElements_db1e1922.o: ../../oscpack/osc/OscPrintReceivedElements.cpp
+$(OBJDIR)/OscPrintReceivedElements_db1e1922.o: /usr/include/oscpack/osc/OscPrintReceivedElements.cpp
         -@mkdir -p $(OBJDIR)
         @echo "Compiling OscPrintReceivedElements.cpp"
         @$(CXX) $(CXXFLAGS) -o "$@" -c "$<"
 
-$(OBJDIR)/OscReceivedElements_b8801585.o: ../../oscpack/osc/OscReceivedElements.cpp
+$(OBJDIR)/OscReceivedElements_b8801585.o: /usr/include/oscpack/osc/OscReceivedElements.cpp
         -@mkdir -p $(OBJDIR)
         @echo "Compiling OscReceivedElements.cpp"
         @$(CXX) $(CXXFLAGS) -o "$@" -c "$<"
 
-$(OBJDIR)/OscTypes_b02e2cd6.o: ../../oscpack/osc/OscTypes.cpp
+$(OBJDIR)/OscTypes_b02e2cd6.o: /usr/include/oscpack/osc/OscTypes.cpp
         -@mkdir -p $(OBJDIR)
         @echo "Compiling OscTypes.cpp"
         @$(CXX) $(CXXFLAGS) -o "$@" -c "$<"
@@ -155,7 +155,7 @@
         @echo "Compiling mlrVSTLookAndFeel.cpp"
         @$(CXX) $(CXXFLAGS) -o "$@" -c "$<"
 
-$(OBJDIR)/juce_VST_Wrapper_812bffb1.o: ../../../../../src/audio/plugin_client/VST/juce_VST_Wrapper.cpp
+$(OBJDIR)/juce_VST_Wrapper_812bffb1.o: /usr/include/juce/src/audio/plugin_client/VST/juce_VST_Wrapper.cpp
         -@mkdir -p $(OBJDIR)
         @echo "Compiling juce_VST_Wrapper.cpp"
         @$(CXX) $(CXXFLAGS) -o "$@" -c "$<"
