--- Makefile	2011-09-19 01:12:12.000000000 -0700
+++ Makefile	2011-09-19 01:13:03.000000000 -0700
@@ -7,7 +7,7 @@
 # CPU optimization section
 #############################################################
 
-OPTFLAGS =  -O2
+OPTFLAGS ?=  -O2
 
 ifdef MAC
 OPTFLAGS += -D_MAC -mcpu=7450
@@ -30,8 +30,8 @@
 # we MUST have -fomit-frame-pointer and -lm, otherwise we hate life
 CFLAGS = $(OPTFLAGS) -s -I.
 # CFLAGS += -Wshadow
-CC=gcc
-CXX=g++
+CC ?= gcc
+CXX ?= g++
 
 COMMON_OBJS = WDL/jnetlib/asyncdns.o
 COMMON_OBJS += WDL/jnetlib/connection.o
